---
abstract: 'Perl extention to do something'
author:
  - 'Kenta Sato <karupa@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
  Test::Requires: 0.06
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: HTML::Lint::Pluggable
name: HTML-Lint-Pluggable
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
